api-endpoint: "https://your-openai-endpoint/v1/chat/completions"
model: "gpt-3.5-turbo"
api-key: "YOUR_OPENAI_API_KEY"
timeout-seconds: 30
max-tokens: 150
temperature: 0.7
history-per-page: 20
waiting-message: "正在请求 AI，请稍候..."
AI-response-prefix: "§bAI: §f"