# —— 全局配置 ——
api-endpoint: "https://your-openai-endpoint/v1/chat/completions"
model: "gpt-3.5-turbo"
api-key: "YOUR_OPENAI_API_KEY"
timeout-seconds: 30
system-message: "You are a helpful assistant."  # AI 设定提示词

# —— 本插件专属配置 —— 
register-ai-command: true        # 是否注册 aichat/ai 指令
rate-limit-count: 5              # 每个玩家在 interval 分钟内可调用次数上限
rate-limit-interval: 1           # 限制时间窗，单位：分钟
history-per-page: 20             # history 指令每页显示的历史记录条数
exceed-limit-message: "你的请求过于频繁，请%wait%秒后再试。"  # 当调用次数超过上限时的提示信息
waiting-message: "正在请求 AI，请稍候..."          # 等待 AI 回复时的提示信息
AI-response-prefix: "§bAI: §f"                  # AI 回复的前缀
max-tokens: 150                                 # AI 回复的最大长度
temperature: 0.7                                # AI 回复的随机性